/* Lista os gastos de cada usuário em cada caravana que ele participou, mostrando custo base e total */
SELECT E.USUARIO, (SUM(G.GASTOS_GANHOS)+ AD.CUSTO_BASE) AS GASTOS_TOTAIS, I.ORGANIZADOR, I.CODIGO_INTERNO 
    FROM ENTRA E JOIN GRUPO_DE_PARTICIPANTES G 
    ON (E.ATIVIDADE = G.ATIVIDADE AND E.CATEGORIA = G.CATEGORIA) JOIN ATIVIDADE A 
    ON (G.ATIVIDADE = A.ID) JOIN ADENTRA AD 
    ON (A.ITINERARIO = AD.ITINERARIO AND E.USUARIO = AD.USUARIO) JOIN ITINERARIO I 
    ON (AD.ITINERARIO = I.ID) JOIN CARAVANA C
    ON (I.ORGANIZADOR = C.ORGANIZADOR AND I.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN PARTICIPA P
    ON (P.ORGANIZADOR = C.ORGANIZADOR AND P.CODIGO_INTERNO = C.CODIGO_INTERNO) 
    GROUP BY E.USUARIO, AD.CUSTO_BASE, I.ORGANIZADOR, I.CODIGO_INTERNO HAVING (SUM(G.GASTOS_GANHOS) + AD.CUSTO_BASE) >= 0;

/* nanana */
SELECT E.USUARIO, -1*(SUM(G.GASTOS_GANHOS)+ AD.CUSTO_BASE) AS GANHOS_TOTAIS, I.ORGANIZADOR, I.CODIGO_INTERNO 
    FROM ENTRA E JOIN GRUPO_DE_PARTICIPANTES G 
    ON (E.ATIVIDADE = G.ATIVIDADE AND E.CATEGORIA = G.CATEGORIA) JOIN ATIVIDADE A 
    ON (G.ATIVIDADE = A.ID) JOIN ADENTRA AD 
    ON (A.ITINERARIO = AD.ITINERARIO AND E.USUARIO = AD.USUARIO) JOIN ITINERARIO I 
    ON (AD.ITINERARIO = I.ID) JOIN CARAVANA C
    ON (I.ORGANIZADOR = C.ORGANIZADOR AND I.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN AUXILIA AU
    ON (AU.ORGANIZADOR = C.ORGANIZADOR AND AU.CODIGO_INTERNO = C.CODIGO_INTERNO) 
    GROUP BY E.USUARIO, AD.CUSTO_BASE, I.ORGANIZADOR, I.CODIGO_INTERNO HAVING (SUM(G.GASTOS_GANHOS) + AD.CUSTO_BASE) <= 0;

/* Lista todas as transferências que os usuários fizeram, ordenando das mais antigas para as mais recentes */
/*  */
