/* CONTA OS GASTOS TOTAIS DO MOCHILEIRO */
SELECT M.MOCHILEIRO, SUM(M.GASTOS_ATIVIDADES_TOTAIS)+SUM(B.CUSTO_BASE_TOTAL) AS GASTOS_TOTAIS, M.ORGANIZADOR, M.CODIGO_INTERNO
    FROM (
        SELECT P.MOCHILEIRO, (SUM(G.GASTOS_GANHOS)) AS GASTOS_ATIVIDADES_TOTAIS, C.ORGANIZADOR, C.CODIGO_INTERNO 
        FROM PARTICIPA P JOIN CARAVANA C
        ON (P.ORGANIZADOR = C.ORGANIZADOR AND P.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ITINERARIO I
        ON (C.ORGANIZADOR = I.ORGANIZADOR AND C.CODIGO_INTERNO = I.CODIGO_INTERNO) JOIN ADENTRA AD
        ON (I.ID = AD.ITINERARIO) JOIN ATIVIDADE A
        ON (AD.ITINERARIO = A.ITINERARIO) JOIN GRUPO_DE_PARTICIPANTES G
        ON (A.ID = G.ATIVIDADE) JOIN ENTRA E
        ON (G.ATIVIDADE = E.ATIVIDADE AND G.CATEGORIA = E.CATEGORIA AND P.MOCHILEIRO = E.USUARIO AND E.USUARIO = AD.USUARIO)
        GROUP BY P.MOCHILEIRO, C.ORGANIZADOR, C.CODIGO_INTERNO
    ) M
    JOIN (
        SELECT AD.USUARIO, SUM(AD.CUSTO_BASE) AS CUSTO_BASE_TOTAL, C.ORGANIZADOR, C.CODIGO_INTERNO
        FROM CARAVANA C JOIN ITINERARIO I
        ON (I.ORGANIZADOR = C.ORGANIZADOR AND I.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ADENTRA AD
        ON (I.ID = AD.ITINERARIO)
        GROUP BY C.ORGANIZADOR, C.CODIGO_INTERNO, AD.USUARIO
    ) B 
    ON (M.MOCHILEIRO = B.USUARIO AND M.ORGANIZADOR = B.ORGANIZADOR AND M.CODIGO_INTERNO = B.CODIGO_INTERNO)
    GROUP BY M.MOCHILEIRO, M.ORGANIZADOR, M.CODIGO_INTERNO;

/* conta os ganhos do especialista */
SELECT E.ESPECIALISTA, SUM(E.GANHOS_ATIVIDADES_TOTAIS)-SUM(B.CUSTO_BASE_TOTAL) AS GANHOS_TOTAIS, E.ORGANIZADOR, E.CODIGO_INTERNO
    FROM (
        SELECT AU.ESPECIALISTA, -1*(SUM(G.GASTOS_GANHOS)) AS GANHOS_ATIVIDADES_TOTAIS, C.ORGANIZADOR, C.CODIGO_INTERNO 
        FROM AUXILIA AU JOIN CARAVANA C
        ON (AU.ORGANIZADOR = C.ORGANIZADOR AND AU.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ITINERARIO I
        ON (C.ORGANIZADOR = I.ORGANIZADOR AND C.CODIGO_INTERNO = I.CODIGO_INTERNO) JOIN ADENTRA AD
        ON (I.ID = AD.ITINERARIO) JOIN ATIVIDADE A
        ON (AD.ITINERARIO = A.ITINERARIO) JOIN GRUPO_DE_PARTICIPANTES G
        ON (A.ID = G.ATIVIDADE) JOIN ENTRA E
        ON (G.ATIVIDADE = E.ATIVIDADE AND G.CATEGORIA = E.CATEGORIA AND AU.ESPECIALISTA = E.USUARIO AND E.USUARIO = AD.USUARIO)
        GROUP BY AU.ESPECIALISTA, C.ORGANIZADOR, C.CODIGO_INTERNO
    ) E
    JOIN (
        SELECT AD.USUARIO, SUM(AD.CUSTO_BASE) AS CUSTO_BASE_TOTAL, C.ORGANIZADOR, C.CODIGO_INTERNO
        FROM CARAVANA C JOIN ITINERARIO I
        ON (I.ORGANIZADOR = C.ORGANIZADOR AND I.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ADENTRA AD
        ON (I.ID = AD.ITINERARIO)
        GROUP BY C.ORGANIZADOR, C.CODIGO_INTERNO, AD.USUARIO
    ) B 
    ON (E.ESPECIALISTA = B.USUARIO AND E.ORGANIZADOR = B.ORGANIZADOR AND E.CODIGO_INTERNO = B.CODIGO_INTERNO)
    GROUP BY E.ESPECIALISTA, E.ORGANIZADOR, E.CODIGO_INTERNO;

/* CONTA OS GANHOS DO ORGANIZADOR */
SELECT U.ORGANIZADOR, U.CODIGO_INTERNO, U.USUARIO, SUM(B.CUSTO_BASE_TOTAL)-SUM(U.GANHOS_ATIVIDADES_TOTAIS) AS GANHOS_TOTAIS
    FROM (
        SELECT P.MOCHILEIRO AS USUARIO, -1*(SUM(G.GASTOS_GANHOS)) AS GANHOS_ATIVIDADES_TOTAIS, C.ORGANIZADOR, C.CODIGO_INTERNO 
        FROM PARTICIPA P JOIN CARAVANA C
        ON (P.ORGANIZADOR = C.ORGANIZADOR AND P.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ITINERARIO I
        ON (C.ORGANIZADOR = I.ORGANIZADOR AND C.CODIGO_INTERNO = I.CODIGO_INTERNO) JOIN ADENTRA AD
        ON (I.ID = AD.ITINERARIO) JOIN ATIVIDADE A
        ON (AD.ITINERARIO = A.ITINERARIO) JOIN GRUPO_DE_PARTICIPANTES G
        ON (A.ID = G.ATIVIDADE) JOIN ENTRA E
        ON (G.ATIVIDADE = E.ATIVIDADE AND G.CATEGORIA = E.CATEGORIA AND P.MOCHILEIRO = E.USUARIO AND E.USUARIO = AD.USUARIO)
        GROUP BY P.MOCHILEIRO, C.ORGANIZADOR, C.CODIGO_INTERNO
        
        UNION

        SELECT AU.ESPECIALISTA AS USUARIO, -1*(SUM(G.GASTOS_GANHOS)) AS GANHOS_ATIVIDADES_TOTAIS, C.ORGANIZADOR, C.CODIGO_INTERNO 
        FROM AUXILIA AU JOIN CARAVANA C
        ON (AU.ORGANIZADOR = C.ORGANIZADOR AND AU.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ITINERARIO I
        ON (C.ORGANIZADOR = I.ORGANIZADOR AND C.CODIGO_INTERNO = I.CODIGO_INTERNO) JOIN ADENTRA AD
        ON (I.ID = AD.ITINERARIO) JOIN ATIVIDADE A
        ON (AD.ITINERARIO = A.ITINERARIO) JOIN GRUPO_DE_PARTICIPANTES G
        ON (A.ID = G.ATIVIDADE) JOIN ENTRA E
        ON (G.ATIVIDADE = E.ATIVIDADE AND G.CATEGORIA = E.CATEGORIA AND AU.ESPECIALISTA = E.USUARIO AND E.USUARIO = AD.USUARIO)
        GROUP BY AU.ESPECIALISTA, C.ORGANIZADOR, C.CODIGO_INTERNO

    ) U
    JOIN (
        SELECT AD.USUARIO, SUM(AD.CUSTO_BASE) AS CUSTO_BASE_TOTAL, C.ORGANIZADOR, C.CODIGO_INTERNO
        FROM CARAVANA C JOIN ITINERARIO I
        ON (I.ORGANIZADOR = C.ORGANIZADOR AND I.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ADENTRA AD
        ON (I.ID = AD.ITINERARIO)
        GROUP BY C.ORGANIZADOR, C.CODIGO_INTERNO, AD.USUARIO
    ) B 
    ON (U.USUARIO = B.USUARIO AND U.ORGANIZADOR = B.ORGANIZADOR AND U.CODIGO_INTERNO = B.CODIGO_INTERNO)
    GROUP BY U.USUARIO, U.ORGANIZADOR, U.CODIGO_INTERNO;

/* Lista as caravanas abertas atualmente */
SELECT AU.ESPECIALISTA AS USUARIO, -1*(SUM(G.GASTOS_GANHOS)) AS GANHOS_ATIVIDADES_TOTAIS, C.ORGANIZADOR, C.CODIGO_INTERNO 
    FROM AUXILIA AU JOIN CARAVANA C
    ON (AU.ORGANIZADOR = C.ORGANIZADOR AND AU.CODIGO_INTERNO = C.CODIGO_INTERNO) JOIN ITINERARIO I
    ON (C.ORGANIZADOR = I.ORGANIZADOR AND C.CODIGO_INTERNO = I.CODIGO_INTERNO) JOIN ADENTRA AD
    ON (I.ID = AD.ITINERARIO) JOIN ATIVIDADE A
    ON (AD.ITINERARIO = A.ITINERARIO) JOIN GRUPO_DE_PARTICIPANTES G
    ON (A.ID = G.ATIVIDADE) JOIN ENTRA E
    ON (G.ATIVIDADE = E.ATIVIDADE AND G.CATEGORIA = E.CATEGORIA AND AU.ESPECIALISTA = E.USUARIO AND E.USUARIO = AD.USUARIO)
    GROUP BY AU.ESPECIALISTA, C.ORGANIZADOR, C.CODIGO_INTERNO;

/* PROCURA NO BANCO A ESTADIA COM A MENOR RELAÇÃO VAGAS/PREÇO */
SELECT *, AGE(C.PARTIDA, CURRENT_TIMESTAMP) 
    AS REMAINING_TIME FROM CARAVANA C 
    WHERE EXTRACT(EPOCH FROM(C.PARTIDA - CURRENT_TIMESTAMP)) > 0
    ORDER BY REMAINING_TIME;

/* Conta o número de mochileiros, especialistas e itinerários de cada caravana */
SELECT M.ORGANIZADOR, M.CODIGO_INTERNO, M.NO_MOCHILEIROS, B.NO_ESPECIALISTAS, I.NO_ITINERARIOS
    FROM (
        SELECT C.ORGANIZADOR, C.CODIGO_INTERNO, COUNT(*) AS NO_MOCHILEIROS FROM CARAVANA C JOIN PARTICIPA P
        ON (P.ORGANIZADOR = C.ORGANIZADOR AND P.CODIGO_INTERNO = C.CODIGO_INTERNO)
        GROUP BY C.ORGANIZADOR, C.CODIGO_INTERNO
    ) M
    JOIN (
        SELECT C.ORGANIZADOR, C.CODIGO_INTERNO, COUNT(*) AS NO_ESPECIALISTAS FROM CARAVANA C JOIN AUXILIA AU
        ON (AU.ORGANIZADOR = C.ORGANIZADOR AND AU.CODIGO_INTERNO = C.CODIGO_INTERNO)
        GROUP BY C.ORGANIZADOR, C.CODIGO_INTERNO
    ) B 
    ON (M.ORGANIZADOR = B.ORGANIZADOR AND M.CODIGO_INTERNO = B.CODIGO_INTERNO)
    JOIN (
        SELECT C.ORGANIZADOR, C.CODIGO_INTERNO, COUNT(*) AS NO_ITINERARIOS FROM CARAVANA C JOIN ITINERARIO I
        ON (I.ORGANIZADOR = C.ORGANIZADOR AND I.CODIGO_INTERNO = C.CODIGO_INTERNO)
        GROUP BY C.ORGANIZADOR, C.CODIGO_INTERNO
    ) I 
    ON (M.ORGANIZADOR = I.ORGANIZADOR AND M.CODIGO_INTERNO = I.CODIGO_INTERNO)
GROUP BY M.ORGANIZADOR, M.CODIGO_INTERNO, M.NO_MOCHILEIROS, B.NO_ESPECIALISTAS, I.NO_ITINERARIOS;

/* mostra todas as atividades que estão passando por cada ponto turístico */
SELECT P.ID AS ID_PONTO_TURISTICO, P.NOME AS NOME_PONTO_TURISTICO, A.ID AS ID_ATIVIDADE, A.NOME AS NOME_ATIVIDADE
    FROM PONTO_TURISTICO P JOIN ITINERARIO I
        ON (P.ID = I.PONTO_TURISTICO) JOIN ATIVIDADE A
        ON (I.ID = A.ITINERARIO)
        GROUP BY P.ID, P.NOME, A.ID, A.NOME
    ORDER BY P.ID;

/* Conta em quantas mochiladas cada mochileiro já participou */
SELECT P.MOCHILEIRO, COUNT(*) AS QUANTIDADE_DE_MOCHILADAS FROM PARTICIPA P
    GROUP BY P.MOCHILEIRO;